version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: hhru
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  bot:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: hhru
      DB_USER: postgres
      DB_PASSWORD: postgres
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
